//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormotsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class appelant_medecins1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public appelant_medecins1()
        {
            this.dossiers = new HashSet<dossiers1>();
        }
    
        public int Id { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public bool Genre { get; set; }
        public string NumeroTelephonePortable { get; set; }
        public string NumeroTelephoneFixe { get; set; }
        public string Email { get; set; }
        public string Adresse { get; set; }
        public string TiersNom { get; set; }
        public string TiersTelephone { get; set; }
        public string TiersEmail { get; set; }
        public string TiersLienParente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dossiers1> dossiers { get; set; }
    }
}
