//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormotsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulaire_ecv1
    {
        public int Id { get; set; }
        public int IdDossier { get; set; }
        public Nullable<System.DateTime> DtCreation { get; set; }
        public Nullable<System.DateTime> DtDebutEntretien { get; set; }
        public Nullable<System.DateTime> DtFinEntretien { get; set; }
        public Nullable<System.DateTime> DtEvaluation { get; set; }
        public Nullable<bool> PriseTraitementPsychotrope { get; set; }
        public Nullable<bool> AutrePrescriptionPsychotropes { get; set; }
        public Nullable<bool> ContinuerPratiquerRythme { get; set; }
    
        public virtual dossiers1 dossiers { get; set; }
    }
}
